/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_accueil (void);
GtkWidget* create_ajout_menu (void);
GtkWidget* create_modifier_menu (void);
GtkWidget* create_liste_menu (void);
GtkWidget* create_supprimer_menu (void);
GtkWidget* create_meilleur_menu (void);
