/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_accueil (void)
{
  GtkWidget *accueil;
  GtkWidget *fixed1;
  GtkWidget *label19;
  GtkWidget *ToajoutFarah;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *toafficherFarah;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *meuilleurMenuFarah;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *tomodfiFarah;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *toSupprimerFarah;
  GtkWidget *alignment14;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label28;

  accueil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (accueil, 600, 600);
  gtk_window_set_title (GTK_WINDOW (accueil), _("Gestion des menus"));
  gtk_window_set_position (GTK_WINDOW (accueil), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (accueil), FALSE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (accueil), fixed1);

  label19 = gtk_label_new (_("<span font='20' foreground=\"#fd0101\">Accueil</span>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed1), label19, 208, 40);
  gtk_widget_set_size_request (label19, 200, 40);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  ToajoutFarah = gtk_button_new ();
  gtk_widget_show (ToajoutFarah);
  gtk_fixed_put (GTK_FIXED (fixed1), ToajoutFarah, 80, 170);
  gtk_widget_set_size_request (ToajoutFarah, 168, 50);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ToajoutFarah), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Ajouter un menu"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  toafficherFarah = gtk_button_new ();
  gtk_widget_show (toafficherFarah);
  gtk_fixed_put (GTK_FIXED (fixed1), toafficherFarah, 80, 280);
  gtk_widget_set_size_request (toafficherFarah, 168, 50);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (toafficherFarah), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Afficher les menus"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  meuilleurMenuFarah = gtk_button_new ();
  gtk_widget_show (meuilleurMenuFarah);
  gtk_fixed_put (GTK_FIXED (fixed1), meuilleurMenuFarah, 192, 390);
  gtk_widget_set_size_request (meuilleurMenuFarah, 232, 50);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (meuilleurMenuFarah), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Meilleur menu de la semaine"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  tomodfiFarah = gtk_button_new ();
  gtk_widget_show (tomodfiFarah);
  gtk_fixed_put (GTK_FIXED (fixed1), tomodfiFarah, 350, 170);
  gtk_widget_set_size_request (tomodfiFarah, 176, 50);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (tomodfiFarah), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Modifier un menu"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  toSupprimerFarah = gtk_button_new ();
  gtk_widget_show (toSupprimerFarah);
  gtk_fixed_put (GTK_FIXED (fixed1), toSupprimerFarah, 350, 280);
  gtk_widget_set_size_request (toSupprimerFarah, 168, 50);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (toSupprimerFarah), alignment14);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Supprimer un menu"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox13), label28, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ToajoutFarah, "clicked",
                    G_CALLBACK (on_ToajoutFarah_clicked),
                    NULL);
  g_signal_connect ((gpointer) toafficherFarah, "clicked",
                    G_CALLBACK (on_toafficherFarah_clicked),
                    NULL);
  g_signal_connect ((gpointer) meuilleurMenuFarah, "clicked",
                    G_CALLBACK (on_meuilleurMenuFarah_clicked),
                    NULL);
  g_signal_connect ((gpointer) tomodfiFarah, "clicked",
                    G_CALLBACK (on_tomodfiFarah_clicked),
                    NULL);
  g_signal_connect ((gpointer) toSupprimerFarah, "clicked",
                    G_CALLBACK (on_toSupprimerFarah_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (accueil, accueil, "accueil");
  GLADE_HOOKUP_OBJECT (accueil, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (accueil, label19, "label19");
  GLADE_HOOKUP_OBJECT (accueil, ToajoutFarah, "ToajoutFarah");
  GLADE_HOOKUP_OBJECT (accueil, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (accueil, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (accueil, image1, "image1");
  GLADE_HOOKUP_OBJECT (accueil, label1, "label1");
  GLADE_HOOKUP_OBJECT (accueil, toafficherFarah, "toafficherFarah");
  GLADE_HOOKUP_OBJECT (accueil, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (accueil, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (accueil, image3, "image3");
  GLADE_HOOKUP_OBJECT (accueil, label3, "label3");
  GLADE_HOOKUP_OBJECT (accueil, meuilleurMenuFarah, "meuilleurMenuFarah");
  GLADE_HOOKUP_OBJECT (accueil, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (accueil, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (accueil, image4, "image4");
  GLADE_HOOKUP_OBJECT (accueil, label4, "label4");
  GLADE_HOOKUP_OBJECT (accueil, tomodfiFarah, "tomodfiFarah");
  GLADE_HOOKUP_OBJECT (accueil, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (accueil, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (accueil, image2, "image2");
  GLADE_HOOKUP_OBJECT (accueil, label2, "label2");
  GLADE_HOOKUP_OBJECT (accueil, toSupprimerFarah, "toSupprimerFarah");
  GLADE_HOOKUP_OBJECT (accueil, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (accueil, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (accueil, image13, "image13");
  GLADE_HOOKUP_OBJECT (accueil, label28, "label28");

  return accueil;
}

GtkWidget*
create_ajout_menu (void)
{
  GtkWidget *ajout_menu;
  GtkWidget *fixed2;
  GtkWidget *nomMenuFarah;
  GtkWidget *dechetFarah;
  GtkWidget *id_farah;
  GtkWidget *retour_ajout;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label17;
  GtkWidget *radio_p_dej;
  GSList *radio_p_dej_group = NULL;
  GtkWidget *radio_dej;
  GtkWidget *radio_d;
  GtkWidget *label9;
  GtkWidget *label5;
  GtkWidget *label22;
  GtkObject *spinJ_adj;
  GtkWidget *spinJ;
  GtkObject *spinM_adj;
  GtkWidget *spinM;
  GtkObject *spinA_adj;
  GtkWidget *spinA;
  GtkWidget *label8;
  GtkWidget *label7;
  GtkWidget *label6;
  GtkWidget *label38;
  GtkWidget *label37;
  GtkWidget *label36;
  GtkWidget *ajout_farah;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label10;
  GtkWidget *outputAdd;

  ajout_menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajout_menu, 784, 650);
  gtk_window_set_title (GTK_WINDOW (ajout_menu), _("Ajouter un menu"));
  gtk_window_set_position (GTK_WINDOW (ajout_menu), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (ajout_menu), FALSE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajout_menu), fixed2);

  nomMenuFarah = gtk_entry_new ();
  gtk_widget_show (nomMenuFarah);
  gtk_fixed_put (GTK_FIXED (fixed2), nomMenuFarah, 184, 210);
  gtk_widget_set_size_request (nomMenuFarah, 150, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (nomMenuFarah), 8226);

  dechetFarah = gtk_entry_new ();
  gtk_widget_show (dechetFarah);
  gtk_fixed_put (GTK_FIXED (fixed2), dechetFarah, 184, 270);
  gtk_widget_set_size_request (dechetFarah, 150, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (dechetFarah), 8226);

  id_farah = gtk_entry_new ();
  gtk_widget_show (id_farah);
  gtk_fixed_put (GTK_FIXED (fixed2), id_farah, 184, 110);
  gtk_widget_set_size_request (id_farah, 150, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_farah), 8226);

  retour_ajout = gtk_button_new ();
  gtk_widget_show (retour_ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), retour_ajout, 64, 584);
  gtk_widget_set_size_request (retour_ajout, 100, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (retour_ajout), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox8), label17, FALSE, FALSE, 0);

  radio_p_dej = gtk_radio_button_new_with_mnemonic (NULL, _("Petit d\303\251jeuner"));
  gtk_widget_show (radio_p_dej);
  gtk_fixed_put (GTK_FIXED (fixed2), radio_p_dej, 184, 160);
  gtk_widget_set_size_request (radio_p_dej, 128, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_p_dej), radio_p_dej_group);
  radio_p_dej_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_p_dej));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radio_p_dej), TRUE);

  radio_dej = gtk_radio_button_new_with_mnemonic (NULL, _("D\303\251jeuner"));
  gtk_widget_show (radio_dej);
  gtk_fixed_put (GTK_FIXED (fixed2), radio_dej, 360, 160);
  gtk_widget_set_size_request (radio_dej, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_dej), radio_p_dej_group);
  radio_p_dej_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_dej));

  radio_d = gtk_radio_button_new_with_mnemonic (NULL, _("Diner"));
  gtk_widget_show (radio_d);
  gtk_fixed_put (GTK_FIXED (fixed2), radio_d, 520, 160);
  gtk_widget_set_size_request (radio_d, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_d), radio_p_dej_group);
  radio_p_dej_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_d));

  label9 = gtk_label_new (_("Type :"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 64, 160);
  gtk_widget_set_size_request (label9, 112, 24);

  label5 = gtk_label_new (_("ID :"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 108, 110);
  gtk_widget_set_size_request (label5, 40, 32);

  label22 = gtk_label_new (_("<span font='20' foreground=\"#fd0101\">Ajouter un menu</span>"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed2), label22, 296, 32);
  gtk_widget_set_size_request (label22, 220, 40);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  spinJ_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinJ = gtk_spin_button_new (GTK_ADJUSTMENT (spinJ_adj), 1, 0);
  gtk_widget_show (spinJ);
  gtk_fixed_put (GTK_FIXED (fixed2), spinJ, 248, 330);
  gtk_widget_set_size_request (spinJ, 60, 27);

  spinM_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinM = gtk_spin_button_new (GTK_ADJUSTMENT (spinM_adj), 1, 0);
  gtk_widget_show (spinM);
  gtk_fixed_put (GTK_FIXED (fixed2), spinM, 384, 330);
  gtk_widget_set_size_request (spinM, 60, 27);

  spinA_adj = gtk_adjustment_new (1, 2010, 2030, 1, 10, 10);
  spinA = gtk_spin_button_new (GTK_ADJUSTMENT (spinA_adj), 1, 0);
  gtk_widget_show (spinA);
  gtk_fixed_put (GTK_FIXED (fixed2), spinA, 550, 330);
  gtk_widget_set_size_request (spinA, 60, 27);

  label8 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 63, 210);
  gtk_widget_set_size_request (label8, 112, 32);

  label7 = gtk_label_new (_("D\303\251chets :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 68, 275);
  gtk_widget_set_size_request (label7, 80, 24);

  label6 = gtk_label_new (_("Date :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 68, 330);
  gtk_widget_set_size_request (label6, 100, 27);

  label38 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed2), label38, 472, 330);
  gtk_widget_set_size_request (label38, 60, 27);

  label37 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed2), label37, 328, 330);
  gtk_widget_set_size_request (label37, 49, 27);

  label36 = gtk_label_new (_("Jour :"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed2), label36, 184, 330);
  gtk_widget_set_size_request (label36, 49, 27);

  ajout_farah = gtk_button_new ();
  gtk_widget_show (ajout_farah);
  gtk_fixed_put (GTK_FIXED (fixed2), ajout_farah, 344, 408);
  gtk_widget_set_size_request (ajout_farah, 120, 48);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (ajout_farah), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox5), label10, FALSE, FALSE, 0);

  outputAdd = gtk_label_new (_("********************"));
  gtk_widget_show (outputAdd);
  gtk_fixed_put (GTK_FIXED (fixed2), outputAdd, 224, 496);
  gtk_widget_set_size_request (outputAdd, 350, 30);

  g_signal_connect ((gpointer) retour_ajout, "clicked",
                    G_CALLBACK (on_retour_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) radio_p_dej, "toggled",
                    G_CALLBACK (on_radio_p_dej_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio_dej, "toggled",
                    G_CALLBACK (on_radio_dej_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio_d, "toggled",
                    G_CALLBACK (on_radio_d_toggled),
                    NULL);
  g_signal_connect ((gpointer) ajout_farah, "clicked",
                    G_CALLBACK (on_ajout_farah_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_menu, ajout_menu, "ajout_menu");
  GLADE_HOOKUP_OBJECT (ajout_menu, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajout_menu, nomMenuFarah, "nomMenuFarah");
  GLADE_HOOKUP_OBJECT (ajout_menu, dechetFarah, "dechetFarah");
  GLADE_HOOKUP_OBJECT (ajout_menu, id_farah, "id_farah");
  GLADE_HOOKUP_OBJECT (ajout_menu, retour_ajout, "retour_ajout");
  GLADE_HOOKUP_OBJECT (ajout_menu, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (ajout_menu, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (ajout_menu, image8, "image8");
  GLADE_HOOKUP_OBJECT (ajout_menu, label17, "label17");
  GLADE_HOOKUP_OBJECT (ajout_menu, radio_p_dej, "radio_p_dej");
  GLADE_HOOKUP_OBJECT (ajout_menu, radio_dej, "radio_dej");
  GLADE_HOOKUP_OBJECT (ajout_menu, radio_d, "radio_d");
  GLADE_HOOKUP_OBJECT (ajout_menu, label9, "label9");
  GLADE_HOOKUP_OBJECT (ajout_menu, label5, "label5");
  GLADE_HOOKUP_OBJECT (ajout_menu, label22, "label22");
  GLADE_HOOKUP_OBJECT (ajout_menu, spinJ, "spinJ");
  GLADE_HOOKUP_OBJECT (ajout_menu, spinM, "spinM");
  GLADE_HOOKUP_OBJECT (ajout_menu, spinA, "spinA");
  GLADE_HOOKUP_OBJECT (ajout_menu, label8, "label8");
  GLADE_HOOKUP_OBJECT (ajout_menu, label7, "label7");
  GLADE_HOOKUP_OBJECT (ajout_menu, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajout_menu, label38, "label38");
  GLADE_HOOKUP_OBJECT (ajout_menu, label37, "label37");
  GLADE_HOOKUP_OBJECT (ajout_menu, label36, "label36");
  GLADE_HOOKUP_OBJECT (ajout_menu, ajout_farah, "ajout_farah");
  GLADE_HOOKUP_OBJECT (ajout_menu, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (ajout_menu, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (ajout_menu, image5, "image5");
  GLADE_HOOKUP_OBJECT (ajout_menu, label10, "label10");
  GLADE_HOOKUP_OBJECT (ajout_menu, outputAdd, "outputAdd");

  return ajout_menu;
}

GtkWidget*
create_modifier_menu (void)
{
  GtkWidget *modifier_menu;
  GtkWidget *fixed3;
  GtkWidget *nom_mod_farah;
  GtkWidget *id_mod_farah;
  GtkWidget *dechet_mod_farah;
  GtkWidget *label15;
  GtkWidget *label11;
  GtkWidget *label16;
  GtkWidget *comboboxtype_farah;
  GtkWidget *valider_farah;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label12;
  GtkWidget *label14;
  GtkWidget *button2;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label13;
  GtkWidget *label23;
  GtkWidget *retourModif;
  GtkWidget *alignment12;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label24;
  GtkWidget *outputEdit;

  modifier_menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modifier_menu, 784, 500);
  gtk_window_set_title (GTK_WINDOW (modifier_menu), _("Modifier un menu"));
  gtk_window_set_position (GTK_WINDOW (modifier_menu), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (modifier_menu), FALSE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (modifier_menu), fixed3);

  nom_mod_farah = gtk_entry_new ();
  gtk_widget_show (nom_mod_farah);
  gtk_fixed_put (GTK_FIXED (fixed3), nom_mod_farah, 176, 240);
  gtk_widget_set_size_request (nom_mod_farah, 176, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_mod_farah), 8226);

  id_mod_farah = gtk_entry_new ();
  gtk_widget_show (id_mod_farah);
  gtk_fixed_put (GTK_FIXED (fixed3), id_mod_farah, 300, 100);
  gtk_widget_set_size_request (id_mod_farah, 144, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_mod_farah), 8226);

  dechet_mod_farah = gtk_entry_new ();
  gtk_widget_show (dechet_mod_farah);
  gtk_fixed_put (GTK_FIXED (fixed3), dechet_mod_farah, 176, 310);
  gtk_widget_set_size_request (dechet_mod_farah, 176, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (dechet_mod_farah), 8226);

  label15 = gtk_label_new (_("Type :"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 72, 170);
  gtk_widget_set_size_request (label15, 56, 30);

  label11 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 56, 240);
  gtk_widget_set_size_request (label11, 80, 32);

  label16 = gtk_label_new (_("D\303\251chets :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 56, 310);
  gtk_widget_set_size_request (label16, 64, 32);

  comboboxtype_farah = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxtype_farah);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxtype_farah, 176, 170);
  gtk_widget_set_size_request (comboboxtype_farah, 176, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtype_farah), _("Petit d\303\251jeuner"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtype_farah), _("D\303\251jeuner"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtype_farah), _("Diner"));

  valider_farah = gtk_button_new ();
  gtk_widget_show (valider_farah);
  gtk_fixed_put (GTK_FIXED (fixed3), valider_farah, 528, 224);
  gtk_widget_set_size_request (valider_farah, 120, 48);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (valider_farah), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-floppy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox6), label12, FALSE, FALSE, 0);

  label14 = gtk_label_new (_("ID :"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 240, 100);
  gtk_widget_set_size_request (label14, 40, 30);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed3), button2, 470, 100);
  gtk_widget_set_size_request (button2, 104, 30);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button2), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("V\303\251rifier"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox7), label13, FALSE, FALSE, 0);

  label23 = gtk_label_new (_("<span font='20' foreground=\"#fd0101\">Modifier un menu</span>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 288, 24);
  gtk_widget_set_size_request (label23, 220, 40);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  retourModif = gtk_button_new ();
  gtk_widget_show (retourModif);
  gtk_fixed_put (GTK_FIXED (fixed3), retourModif, 88, 432);
  gtk_widget_set_size_request (retourModif, 100, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (retourModif), alignment12);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox11), label24, FALSE, FALSE, 0);

  outputEdit = gtk_label_new (_("*********************"));
  gtk_widget_show (outputEdit);
  gtk_fixed_put (GTK_FIXED (fixed3), outputEdit, 264, 376);
  gtk_widget_set_size_request (outputEdit, 300, 30);

  g_signal_connect ((gpointer) valider_farah, "clicked",
                    G_CALLBACK (on_valider_farah_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_check_id_clicked),
                    NULL);
  g_signal_connect ((gpointer) retourModif, "clicked",
                    G_CALLBACK (on_retourModif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_menu, modifier_menu, "modifier_menu");
  GLADE_HOOKUP_OBJECT (modifier_menu, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modifier_menu, nom_mod_farah, "nom_mod_farah");
  GLADE_HOOKUP_OBJECT (modifier_menu, id_mod_farah, "id_mod_farah");
  GLADE_HOOKUP_OBJECT (modifier_menu, dechet_mod_farah, "dechet_mod_farah");
  GLADE_HOOKUP_OBJECT (modifier_menu, label15, "label15");
  GLADE_HOOKUP_OBJECT (modifier_menu, label11, "label11");
  GLADE_HOOKUP_OBJECT (modifier_menu, label16, "label16");
  GLADE_HOOKUP_OBJECT (modifier_menu, comboboxtype_farah, "comboboxtype_farah");
  GLADE_HOOKUP_OBJECT (modifier_menu, valider_farah, "valider_farah");
  GLADE_HOOKUP_OBJECT (modifier_menu, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (modifier_menu, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (modifier_menu, image6, "image6");
  GLADE_HOOKUP_OBJECT (modifier_menu, label12, "label12");
  GLADE_HOOKUP_OBJECT (modifier_menu, label14, "label14");
  GLADE_HOOKUP_OBJECT (modifier_menu, button2, "button2");
  GLADE_HOOKUP_OBJECT (modifier_menu, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (modifier_menu, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (modifier_menu, image7, "image7");
  GLADE_HOOKUP_OBJECT (modifier_menu, label13, "label13");
  GLADE_HOOKUP_OBJECT (modifier_menu, label23, "label23");
  GLADE_HOOKUP_OBJECT (modifier_menu, retourModif, "retourModif");
  GLADE_HOOKUP_OBJECT (modifier_menu, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (modifier_menu, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (modifier_menu, image11, "image11");
  GLADE_HOOKUP_OBJECT (modifier_menu, label24, "label24");
  GLADE_HOOKUP_OBJECT (modifier_menu, outputEdit, "outputEdit");

  return modifier_menu;
}

GtkWidget*
create_liste_menu (void)
{
  GtkWidget *liste_menu;
  GtkWidget *fixed4;
  GtkWidget *label18;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeviewFarah;
  GtkWidget *button3;
  GtkWidget *alignment10;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label20;
  GtkWidget *Retour_list;
  GtkWidget *alignment11;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label21;

  liste_menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (liste_menu, 824, 600);
  gtk_window_set_title (GTK_WINDOW (liste_menu), _("Liste des menus"));
  gtk_window_set_position (GTK_WINDOW (liste_menu), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (liste_menu), FALSE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (liste_menu), fixed4);

  label18 = gtk_label_new (_("<span font='20' foreground=\"#fd0101\">Liste des menus </span>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 280, 16);
  gtk_widget_set_size_request (label18, 280, 56);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow1, 80, 120);
  gtk_widget_set_size_request (scrolledwindow1, 700, 340);

  treeviewFarah = gtk_tree_view_new ();
  gtk_widget_show (treeviewFarah);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeviewFarah);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed4), button3, 408, 480);
  gtk_widget_set_size_request (button3, 112, 48);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button3), alignment10);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox9), label20, FALSE, FALSE, 0);

  Retour_list = gtk_button_new ();
  gtk_widget_show (Retour_list);
  gtk_fixed_put (GTK_FIXED (fixed4), Retour_list, 32, 536);
  gtk_widget_set_size_request (Retour_list, 100, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (Retour_list), alignment11);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox10), label21, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_affichage_clicked),
                    NULL);
  g_signal_connect ((gpointer) Retour_list, "clicked",
                    G_CALLBACK (on_Retour_list_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (liste_menu, liste_menu, "liste_menu");
  GLADE_HOOKUP_OBJECT (liste_menu, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (liste_menu, label18, "label18");
  GLADE_HOOKUP_OBJECT (liste_menu, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (liste_menu, treeviewFarah, "treeviewFarah");
  GLADE_HOOKUP_OBJECT (liste_menu, button3, "button3");
  GLADE_HOOKUP_OBJECT (liste_menu, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (liste_menu, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (liste_menu, image9, "image9");
  GLADE_HOOKUP_OBJECT (liste_menu, label20, "label20");
  GLADE_HOOKUP_OBJECT (liste_menu, Retour_list, "Retour_list");
  GLADE_HOOKUP_OBJECT (liste_menu, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (liste_menu, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (liste_menu, image10, "image10");
  GLADE_HOOKUP_OBJECT (liste_menu, label21, "label21");

  return liste_menu;
}

GtkWidget*
create_supprimer_menu (void)
{
  GtkWidget *supprimer_menu;
  GtkWidget *fixed5;
  GtkWidget *id_supp_farah;
  GtkWidget *label26;
  GtkWidget *supprimer_farah;
  GtkWidget *alignment13;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label27;
  GtkWidget *retour_supp;
  GtkWidget *alignment15;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label29;
  GtkWidget *label25;
  GtkWidget *outputDel;

  supprimer_menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (supprimer_menu, 700, 450);
  gtk_window_set_title (GTK_WINDOW (supprimer_menu), _("Supprimer Menu"));
  gtk_window_set_position (GTK_WINDOW (supprimer_menu), GTK_WIN_POS_CENTER);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (supprimer_menu), fixed5);

  id_supp_farah = gtk_entry_new ();
  gtk_widget_show (id_supp_farah);
  gtk_fixed_put (GTK_FIXED (fixed5), id_supp_farah, 258, 176);
  gtk_widget_set_size_request (id_supp_farah, 160, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_supp_farah), 8226);

  label26 = gtk_label_new (_("ID :"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed5), label26, 184, 176);
  gtk_widget_set_size_request (label26, 49, 30);

  supprimer_farah = gtk_button_new ();
  gtk_widget_show (supprimer_farah);
  gtk_fixed_put (GTK_FIXED (fixed5), supprimer_farah, 440, 176);
  gtk_widget_set_size_request (supprimer_farah, 100, 30);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (supprimer_farah), alignment13);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox12), label27, FALSE, FALSE, 0);

  retour_supp = gtk_button_new ();
  gtk_widget_show (retour_supp);
  gtk_fixed_put (GTK_FIXED (fixed5), retour_supp, 64, 376);
  gtk_widget_set_size_request (retour_supp, 100, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (retour_supp), alignment15);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox14), label29, FALSE, FALSE, 0);

  label25 = gtk_label_new (_("<span font='20' foreground='#fd0101'>Supprimer Menu</span>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed5), label25, 248, 24);
  gtk_widget_set_size_request (label25, 220, 40);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  outputDel = gtk_label_new (_("***********************"));
  gtk_widget_show (outputDel);
  gtk_fixed_put (GTK_FIXED (fixed5), outputDel, 192, 272);
  gtk_widget_set_size_request (outputDel, 350, 30);

  g_signal_connect ((gpointer) supprimer_farah, "clicked",
                    G_CALLBACK (on_supprimer_farah_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_supp, "clicked",
                    G_CALLBACK (on_retour_supp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_menu, supprimer_menu, "supprimer_menu");
  GLADE_HOOKUP_OBJECT (supprimer_menu, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (supprimer_menu, id_supp_farah, "id_supp_farah");
  GLADE_HOOKUP_OBJECT (supprimer_menu, label26, "label26");
  GLADE_HOOKUP_OBJECT (supprimer_menu, supprimer_farah, "supprimer_farah");
  GLADE_HOOKUP_OBJECT (supprimer_menu, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (supprimer_menu, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (supprimer_menu, image12, "image12");
  GLADE_HOOKUP_OBJECT (supprimer_menu, label27, "label27");
  GLADE_HOOKUP_OBJECT (supprimer_menu, retour_supp, "retour_supp");
  GLADE_HOOKUP_OBJECT (supprimer_menu, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (supprimer_menu, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (supprimer_menu, image14, "image14");
  GLADE_HOOKUP_OBJECT (supprimer_menu, label29, "label29");
  GLADE_HOOKUP_OBJECT (supprimer_menu, label25, "label25");
  GLADE_HOOKUP_OBJECT (supprimer_menu, outputDel, "outputDel");

  return supprimer_menu;
}

GtkWidget*
create_meilleur_menu (void)
{
  GtkWidget *meilleur_menu;
  GtkWidget *fixed6;
  GtkWidget *retourMeui_farah;
  GtkWidget *alignment16;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label35;
  GtkWidget *label31;
  GtkWidget *id_menu;
  GtkWidget *label33;
  GtkWidget *nom_Mmenu;
  GtkWidget *label30;
  GtkObject *JD_adj;
  GtkWidget *JD;
  GtkObject *MD_adj;
  GtkWidget *MD;
  GtkObject *AD_adj;
  GtkWidget *AD;
  GtkWidget *label40;
  GtkObject *JA_adj;
  GtkWidget *JA;
  GtkObject *MA_adj;
  GtkWidget *MA;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkObject *AA_adj;
  GtkWidget *AA;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *label39;
  GtkWidget *label43;
  GtkWidget *trouverM;
  GtkWidget *alignment17;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label47;

  meilleur_menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (meilleur_menu, 650, 600);
  gtk_window_set_title (GTK_WINDOW (meilleur_menu), _("Meilleur menu"));
  gtk_window_set_position (GTK_WINDOW (meilleur_menu), GTK_WIN_POS_CENTER);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (meilleur_menu), fixed6);

  retourMeui_farah = gtk_button_new ();
  gtk_widget_show (retourMeui_farah);
  gtk_fixed_put (GTK_FIXED (fixed6), retourMeui_farah, 40, 536);
  gtk_widget_set_size_request (retourMeui_farah, 100, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (retourMeui_farah), alignment16);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox15), label35, FALSE, FALSE, 0);

  label31 = gtk_label_new (_("ID :"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed6), label31, 224, 384);
  gtk_widget_set_size_request (label31, 50, 30);

  id_menu = gtk_label_new (_("******"));
  gtk_widget_show (id_menu);
  gtk_fixed_put (GTK_FIXED (fixed6), id_menu, 320, 384);
  gtk_widget_set_size_request (id_menu, 140, 30);

  label33 = gtk_label_new (_("Nom menu :"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed6), label33, 168, 432);
  gtk_widget_set_size_request (label33, 100, 30);

  nom_Mmenu = gtk_label_new (_("******"));
  gtk_widget_show (nom_Mmenu);
  gtk_fixed_put (GTK_FIXED (fixed6), nom_Mmenu, 320, 440);
  gtk_widget_set_size_request (nom_Mmenu, 140, 30);

  label30 = gtk_label_new (_("<span font='20' foreground='#fd0101'>Meilleur Menu</span>"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed6), label30, 232, 24);
  gtk_widget_set_size_request (label30, 220, 40);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  JD_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  JD = gtk_spin_button_new (GTK_ADJUSTMENT (JD_adj), 1, 0);
  gtk_widget_show (JD);
  gtk_fixed_put (GTK_FIXED (fixed6), JD, 216, 140);
  gtk_widget_set_size_request (JD, 60, 27);

  MD_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  MD = gtk_spin_button_new (GTK_ADJUSTMENT (MD_adj), 1, 0);
  gtk_widget_show (MD);
  gtk_fixed_put (GTK_FIXED (fixed6), MD, 345, 140);
  gtk_widget_set_size_request (MD, 60, 27);

  AD_adj = gtk_adjustment_new (2020, 2010, 2030, 1, 10, 10);
  AD = gtk_spin_button_new (GTK_ADJUSTMENT (AD_adj), 1, 0);
  gtk_widget_show (AD);
  gtk_fixed_put (GTK_FIXED (fixed6), AD, 480, 140);
  gtk_widget_set_size_request (AD, 60, 27);

  label40 = gtk_label_new (_("Jour :"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed6), label40, 168, 140);
  gtk_widget_set_size_request (label40, 49, 27);

  JA_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  JA = gtk_spin_button_new (GTK_ADJUSTMENT (JA_adj), 1, 0);
  gtk_widget_show (JA);
  gtk_fixed_put (GTK_FIXED (fixed6), JA, 216, 210);
  gtk_widget_set_size_request (JA, 60, 27);

  MA_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  MA = gtk_spin_button_new (GTK_ADJUSTMENT (MA_adj), 1, 0);
  gtk_widget_show (MA);
  gtk_fixed_put (GTK_FIXED (fixed6), MA, 345, 210);
  gtk_widget_set_size_request (MA, 60, 27);

  label41 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed6), label41, 295, 140);
  gtk_widget_set_size_request (label41, 49, 27);

  label42 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed6), label42, 427, 140);
  gtk_widget_set_size_request (label42, 49, 27);

  AA_adj = gtk_adjustment_new (2021, 2010, 2030, 1, 10, 10);
  AA = gtk_spin_button_new (GTK_ADJUSTMENT (AA_adj), 1, 0);
  gtk_widget_show (AA);
  gtk_fixed_put (GTK_FIXED (fixed6), AA, 480, 210);
  gtk_widget_set_size_request (AA, 60, 27);

  label44 = gtk_label_new (_("Jour :"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed6), label44, 168, 210);
  gtk_widget_set_size_request (label44, 49, 27);

  label45 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed6), label45, 295, 210);
  gtk_widget_set_size_request (label45, 49, 27);

  label46 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed6), label46, 427, 210);
  gtk_widget_set_size_request (label46, 49, 27);

  label39 = gtk_label_new (_("De :"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed6), label39, 88, 140);
  gtk_widget_set_size_request (label39, 50, 27);

  label43 = gtk_label_new (_("\303\200 :"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed6), label43, 88, 210);
  gtk_widget_set_size_request (label43, 50, 27);

  trouverM = gtk_button_new ();
  gtk_widget_show (trouverM);
  gtk_fixed_put (GTK_FIXED (fixed6), trouverM, 260, 296);
  gtk_widget_set_size_request (trouverM, 120, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (trouverM), alignment17);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Trouver"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox16), label47, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) retourMeui_farah, "clicked",
                    G_CALLBACK (on_retourMeui_farah_clicked),
                    NULL);
  g_signal_connect ((gpointer) trouverM, "clicked",
                    G_CALLBACK (on_trouverM_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (meilleur_menu, meilleur_menu, "meilleur_menu");
  GLADE_HOOKUP_OBJECT (meilleur_menu, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (meilleur_menu, retourMeui_farah, "retourMeui_farah");
  GLADE_HOOKUP_OBJECT (meilleur_menu, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (meilleur_menu, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (meilleur_menu, image15, "image15");
  GLADE_HOOKUP_OBJECT (meilleur_menu, label35, "label35");
  GLADE_HOOKUP_OBJECT (meilleur_menu, label31, "label31");
  GLADE_HOOKUP_OBJECT (meilleur_menu, id_menu, "id_menu");
  GLADE_HOOKUP_OBJECT (meilleur_menu, label33, "label33");
  GLADE_HOOKUP_OBJECT (meilleur_menu, nom_Mmenu, "nom_Mmenu");
  GLADE_HOOKUP_OBJECT (meilleur_menu, label30, "label30");
  GLADE_HOOKUP_OBJECT (meilleur_menu, JD, "JD");
  GLADE_HOOKUP_OBJECT (meilleur_menu, MD, "MD");
  GLADE_HOOKUP_OBJECT (meilleur_menu, AD, "AD");
  GLADE_HOOKUP_OBJECT (meilleur_menu, label40, "label40");
  GLADE_HOOKUP_OBJECT (meilleur_menu, JA, "JA");
  GLADE_HOOKUP_OBJECT (meilleur_menu, MA, "MA");
  GLADE_HOOKUP_OBJECT (meilleur_menu, label41, "label41");
  GLADE_HOOKUP_OBJECT (meilleur_menu, label42, "label42");
  GLADE_HOOKUP_OBJECT (meilleur_menu, AA, "AA");
  GLADE_HOOKUP_OBJECT (meilleur_menu, label44, "label44");
  GLADE_HOOKUP_OBJECT (meilleur_menu, label45, "label45");
  GLADE_HOOKUP_OBJECT (meilleur_menu, label46, "label46");
  GLADE_HOOKUP_OBJECT (meilleur_menu, label39, "label39");
  GLADE_HOOKUP_OBJECT (meilleur_menu, label43, "label43");
  GLADE_HOOKUP_OBJECT (meilleur_menu, trouverM, "trouverM");
  GLADE_HOOKUP_OBJECT (meilleur_menu, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (meilleur_menu, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (meilleur_menu, image16, "image16");
  GLADE_HOOKUP_OBJECT (meilleur_menu, label47, "label47");

  return meilleur_menu;
}

