/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *accueil;
  GtkWidget *ajout_menu;
  GtkWidget *modifier_menu;
  GtkWidget *liste_menu;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  accueil = create_accueil ();
  gtk_widget_show (accueil);
  /*ajout_menu = create_ajout_menu ();
  gtk_widget_show (ajout_menu);
  modifier_menu = create_modifier_menu ();
  gtk_widget_show (modifier_menu);
  liste_menu = create_liste_menu ();
  gtk_widget_show (liste_menu);*/

  gtk_main ();
  return 0;
}

